#pragma once

#include <SDL/SDL_events.h>

enum SDL_ScanCode {
    // Letters
    SDL_SCANCODE_A = SDLK_a,
    SDL_SCANCODE_B = SDLK_b,
    SDL_SCANCODE_C = SDLK_c,
    SDL_SCANCODE_D = SDLK_d,
    SDL_SCANCODE_E = SDLK_e,
    SDL_SCANCODE_F = SDLK_f,
    SDL_SCANCODE_G = SDLK_g,
    SDL_SCANCODE_H = SDLK_h,
    SDL_SCANCODE_I = SDLK_i,
    SDL_SCANCODE_J = SDLK_j,
    SDL_SCANCODE_K = SDLK_k,
    SDL_SCANCODE_L = SDLK_l,
    SDL_SCANCODE_M = SDLK_m,
    SDL_SCANCODE_N = SDLK_n,
    SDL_SCANCODE_O = SDLK_o,
    SDL_SCANCODE_P = SDLK_p,
    SDL_SCANCODE_Q = SDLK_q,
    SDL_SCANCODE_R = SDLK_r,
    SDL_SCANCODE_S = SDLK_s,
    SDL_SCANCODE_T = SDLK_t,
    SDL_SCANCODE_U = SDLK_u,
    SDL_SCANCODE_V = SDLK_v,
    SDL_SCANCODE_W = SDLK_w,
    SDL_SCANCODE_X = SDLK_x,
    SDL_SCANCODE_Y = SDLK_y,
    SDL_SCANCODE_Z = SDLK_z,

    // Numbers
    SDL_SCANCODE_0 = SDLK_0,
    SDL_SCANCODE_1 = SDLK_1,
    SDL_SCANCODE_2 = SDLK_2,
    SDL_SCANCODE_3 = SDLK_3,
    SDL_SCANCODE_4 = SDLK_4,
    SDL_SCANCODE_5 = SDLK_5,
    SDL_SCANCODE_6 = SDLK_6,
    SDL_SCANCODE_7 = SDLK_7,
    SDL_SCANCODE_8 = SDLK_8,
    SDL_SCANCODE_9 = SDLK_9,

    // Function keys
    SDL_SCANCODE_F1  = SDLK_F1,
    SDL_SCANCODE_F2  = SDLK_F2,
    SDL_SCANCODE_F3  = SDLK_F3,
    SDL_SCANCODE_F4  = SDLK_F4,
    SDL_SCANCODE_F5  = SDLK_F5,
    SDL_SCANCODE_F6  = SDLK_F6,
    SDL_SCANCODE_F7  = SDLK_F7,
    SDL_SCANCODE_F8  = SDLK_F8,
    SDL_SCANCODE_F9  = SDLK_F9,
    SDL_SCANCODE_F10 = SDLK_F10,
    SDL_SCANCODE_F11 = SDLK_F11,
    SDL_SCANCODE_F12 = SDLK_F12,

    // Arrow keys
    SDL_SCANCODE_UP    = SDLK_UP,
    SDL_SCANCODE_DOWN  = SDLK_DOWN,
    SDL_SCANCODE_LEFT  = SDLK_LEFT,
    SDL_SCANCODE_RIGHT = SDLK_RIGHT,

    // Control keys
    SDL_SCANCODE_RETURN    = SDLK_RETURN,
    SDL_SCANCODE_RETURN2   = SDLK_KP_ENTER,
    SDL_SCANCODE_ESCAPE    = SDLK_ESCAPE,
    SDL_SCANCODE_BACKSPACE = SDLK_BACKSPACE,
    SDL_SCANCODE_TAB       = SDLK_TAB,
    SDL_SCANCODE_SPACE     = SDLK_SPACE,
    SDL_SCANCODE_DELETE    = SDLK_DELETE,
    SDL_SCANCODE_INSERT    = SDLK_INSERT,
    SDL_SCANCODE_HOME      = SDLK_HOME,
    SDL_SCANCODE_END       = SDLK_END,
    SDL_SCANCODE_PAGEUP    = SDLK_PAGEUP,
    SDL_SCANCODE_PAGEDOWN  = SDLK_PAGEDOWN,
    SDL_SCANCODE_CAPSLOCK  = SDLK_CAPSLOCK,
    SDL_SCANCODE_PRINTSCREEN = SDLK_PRINT,
    SDL_SCANCODE_SCROLLLOCK  = SDLK_SCROLLOCK,
    SDL_SCANCODE_PAUSE       = SDLK_PAUSE,

    // Modifiers
    SDL_SCANCODE_LSHIFT = SDLK_LSHIFT,
    SDL_SCANCODE_RSHIFT = SDLK_RSHIFT,
    SDL_SCANCODE_LCTRL  = SDLK_LCTRL,
    SDL_SCANCODE_RCTRL  = SDLK_RCTRL,
    SDL_SCANCODE_LALT   = SDLK_LALT,
    SDL_SCANCODE_RALT   = SDLK_RALT,
    SDL_SCANCODE_LGUI   = SDLK_LSUPER,
    SDL_SCANCODE_RGUI   = SDLK_RSUPER,
    SDL_SCANCODE_MODE   = SDLK_MODE,

    // Numpad
    SDL_SCANCODE_KP_0 = SDLK_KP0,
    SDL_SCANCODE_KP_1 = SDLK_KP1,
    SDL_SCANCODE_KP_2 = SDLK_KP2,
    SDL_SCANCODE_KP_3 = SDLK_KP3,
    SDL_SCANCODE_KP_4 = SDLK_KP4,
    SDL_SCANCODE_KP_5 = SDLK_KP5,
    SDL_SCANCODE_KP_6 = SDLK_KP6,
    SDL_SCANCODE_KP_7 = SDLK_KP7,
    SDL_SCANCODE_KP_8 = SDLK_KP8,
    SDL_SCANCODE_KP_9 = SDLK_KP9,
    SDL_SCANCODE_KP_DIVIDE   = SDLK_KP_DIVIDE,
    SDL_SCANCODE_KP_MULTIPLY = SDLK_KP_MULTIPLY,
    SDL_SCANCODE_KP_MINUS    = SDLK_KP_MINUS,
    SDL_SCANCODE_KP_PLUS     = SDLK_KP_PLUS,
    SDL_SCANCODE_KP_ENTER    = SDLK_KP_ENTER,
    SDL_SCANCODE_KP_PERIOD   = SDLK_KP_PERIOD,
    SDL_SCANCODE_KP_EQUALS   = SDLK_KP_EQUALS,

    // Punctuation
    SDL_SCANCODE_MINUS        = SDLK_MINUS,
    SDL_SCANCODE_EQUALS       = SDLK_EQUALS,
    SDL_SCANCODE_LEFTBRACKET  = SDLK_LEFTBRACKET,
    SDL_SCANCODE_RIGHTBRACKET = SDLK_RIGHTBRACKET,
    SDL_SCANCODE_BACKSLASH    = SDLK_BACKSLASH,
    SDL_SCANCODE_SEMICOLON    = SDLK_SEMICOLON,
    SDL_SCANCODE_APOSTROPHE   = SDLK_QUOTE,
    SDL_SCANCODE_GRAVE        = SDLK_BACKQUOTE,
    SDL_SCANCODE_COMMA        = SDLK_COMMA,
    SDL_SCANCODE_PERIOD       = SDLK_PERIOD,
    SDL_SCANCODE_SLASH        = SDLK_SLASH,

    SDL_SCANCODE_UNKNOWN = SDLK_UNKNOWN
};

static inline const Uint8* SDL_GetKeyboardState(int *keynum) {
    static Uint8 *keystates = NULL;

    keystates = SDL_GetKeyState(keynum);

    return (const Uint8*)keystates;
}

//No-Ops
static const int SDL_CONTROLLERDEVICEADDED = -1;