#pragma once

#include "universalsdl.h"

enum LuminaKey {
    // Letters
    LUMINA_KEY_A = SDLK_a,
    LUMINA_KEY_B = SDLK_b,
    LUMINA_KEY_C = SDLK_c,
    LUMINA_KEY_D = SDLK_d,
    LUMINA_KEY_E = SDLK_e,
    LUMINA_KEY_F = SDLK_f,
    LUMINA_KEY_G = SDLK_g,
    LUMINA_KEY_H = SDLK_h,
    LUMINA_KEY_I = SDLK_i,
    LUMINA_KEY_J = SDLK_j,
    LUMINA_KEY_K = SDLK_k,
    LUMINA_KEY_L = SDLK_l,
    LUMINA_KEY_M = SDLK_m,
    LUMINA_KEY_N = SDLK_n,
    LUMINA_KEY_O = SDLK_o,
    LUMINA_KEY_P = SDLK_p,
    LUMINA_KEY_Q = SDLK_q,
    LUMINA_KEY_R = SDLK_r,
    LUMINA_KEY_S = SDLK_s,
    LUMINA_KEY_T = SDLK_t,
    LUMINA_KEY_U = SDLK_u,
    LUMINA_KEY_V = SDLK_v,
    LUMINA_KEY_W = SDLK_w,
    LUMINA_KEY_X = SDLK_x,
    LUMINA_KEY_Y = SDLK_y,
    LUMINA_KEY_Z = SDLK_z,

    // Numbers
    LUMINA_KEY_0 = SDLK_0,
    LUMINA_KEY_1 = SDLK_1,
    LUMINA_KEY_2 = SDLK_2,
    LUMINA_KEY_3 = SDLK_3,
    LUMINA_KEY_4 = SDLK_4,
    LUMINA_KEY_5 = SDLK_5,
    LUMINA_KEY_6 = SDLK_6,
    LUMINA_KEY_7 = SDLK_7,
    LUMINA_KEY_8 = SDLK_8,
    LUMINA_KEY_9 = SDLK_9,

    // Function keys
    LUMINA_KEY_F1  = SDLK_F1,
    LUMINA_KEY_F2  = SDLK_F2,
    LUMINA_KEY_F3  = SDLK_F3,
    LUMINA_KEY_F4  = SDLK_F4,
    LUMINA_KEY_F5  = SDLK_F5,
    LUMINA_KEY_F6  = SDLK_F6,
    LUMINA_KEY_F7  = SDLK_F7,
    LUMINA_KEY_F8  = SDLK_F8,
    LUMINA_KEY_F9  = SDLK_F9,
    LUMINA_KEY_F10 = SDLK_F10,
    LUMINA_KEY_F11 = SDLK_F11,
    LUMINA_KEY_F12 = SDLK_F12,

    // Arrow keys
    LUMINA_KEY_UP    = SDLK_UP,
    LUMINA_KEY_DOWN  = SDLK_DOWN,
    LUMINA_KEY_LEFT  = SDLK_LEFT,
    LUMINA_KEY_RIGHT = SDLK_RIGHT,

    // Control keys
    LUMINA_KEY_RETURN    = SDLK_RETURN,
    LUMINA_KEY_ESCAPE    = SDLK_ESCAPE,
    LUMINA_KEY_BACKSPACE = SDLK_BACKSPACE,
    LUMINA_KEY_TAB       = SDLK_TAB,
    LUMINA_KEY_SPACE     = SDLK_SPACE,
    LUMINA_KEY_DELETE    = SDLK_DELETE,
    LUMINA_KEY_INSERT    = SDLK_INSERT,
    LUMINA_KEY_HOME      = SDLK_HOME,
    LUMINA_KEY_END       = SDLK_END,
    LUMINA_KEY_PAGEUP    = SDLK_PAGEUP,
    LUMINA_KEY_PAGEDOWN  = SDLK_PAGEDOWN,

    // Modifiers
    LUMINA_KEY_LSHIFT = SDLK_LSHIFT,
    LUMINA_KEY_RSHIFT = SDLK_RSHIFT,
    LUMINA_KEY_LCTRL  = SDLK_LCTRL,
    LUMINA_KEY_RCTRL  = SDLK_RCTRL,
    LUMINA_KEY_LALT   = SDLK_LALT,
    LUMINA_KEY_RALT   = SDLK_RALT,

    // Punctuation
    LUMINA_KEY_MINUS     = SDLK_MINUS,
    LUMINA_KEY_EQUALS    = SDLK_EQUALS,
    LUMINA_KEY_LEFTBRACKET  = SDLK_LEFTBRACKET,
    LUMINA_KEY_RIGHTBRACKET = SDLK_RIGHTBRACKET,
    LUMINA_KEY_BACKSLASH = SDLK_BACKSLASH,
    LUMINA_KEY_SEMICOLON = SDLK_SEMICOLON,
    LUMINA_KEY_QUOTE     = SDLK_QUOTE,
    LUMINA_KEY_COMMA     = SDLK_COMMA,
    LUMINA_KEY_PERIOD    = SDLK_PERIOD,
    LUMINA_KEY_SLASH     = SDLK_SLASH,
    LUMINA_KEY_BACKQUOTE = SDLK_BACKQUOTE,

#ifdef PLATFORM_3DS
    // 3DS buttons mapped to SDLKey by the 3DS SDL1.2 port
    LUMINA_GAMEPAD_A      = SDLK_a,    // remap as needed
    LUMINA_GAMEPAD_B      = SDLK_b,
    LUMINA_GAMEPAD_X      = SDLK_x,
    LUMINA_GAMEPAD_Y      = SDLK_y,
    LUMINA_GAMEPAD_L      = SDLK_e,
    LUMINA_GAMEPAD_R      = SDLK_r,
    LUMINA_GAMEPAD_START  = SDLK_RETURN,
    LUMINA_GAMEPAD_SELECT = SDLK_RSHIFT,
    LUMINA_GAMEPAD_DUP    = SDLK_UP,
    LUMINA_GAMEPAD_DDOWN  = SDLK_DOWN,
    LUMINA_GAMEPAD_DLEFT  = SDLK_LEFT,
    LUMINA_GAMEPAD_DRIGHT = SDLK_RIGHT,
#endif

    LUMINA_KEY_UNKNOWN = SDLK_UNKNOWN
};